ecs_cluster_name     = "jolchin-ecs-cluster-prod"
ecs_service_name     = "jolchin-ecs-service-prod"
ecs_task_defn_family = "jolchin-ecs-task-def-prod"
ecs_container_name   = "jolchin-container-prod"
ecs_port_name        = "jolchin-3000-tcp-prod"
