ecs_cluster_name     = "jolchin-ecs-cluster-uat"
ecs_service_name     = "jolchin-ecs-service-uat"
ecs_task_defn_family = "jolchin-ecs-task-def-uat"
ecs_container_name   = "jolchin-container-uat"
ecs_port_name        = "jolchin-3000-tcp-uat"
